-- SGBD ORACLE 11 G

DROP TABLE t_emc_categ_video CASCADE CONSTRAINTS;

DROP TABLE t_emc_cli CASCADE CONSTRAINTS;

DROP TABLE t_emc_cli_email CASCADE CONSTRAINTS;

DROP TABLE t_emc_departamento CASCADE CONSTRAINTS;

DROP TABLE t_emc_emailv1 CASCADE CONSTRAINTS;

DROP TABLE t_emc_emailv2 CASCADE CONSTRAINTS;

DROP TABLE t_emc_fornecedor CASCADE CONSTRAINTS;

DROP TABLE t_emc_func CASCADE CONSTRAINTS;

DROP TABLE t_emc_func_email CASCADE CONSTRAINTS;

DROP TABLE t_emc_func_telf CASCADE CONSTRAINTS;

DROP TABLE t_emc_pf CASCADE CONSTRAINTS;

DROP TABLE t_emc_pj CASCADE CONSTRAINTS;

DROP TABLE t_emc_prod_categoria CASCADE CONSTRAINTS;

DROP TABLE t_emc_prod_fornecedor CASCADE CONSTRAINTS;

DROP TABLE t_emc_produto CASCADE CONSTRAINTS;

DROP TABLE t_emc_sac CASCADE CONSTRAINTS;

DROP TABLE t_emc_telf_cli CASCADE CONSTRAINTS;

DROP TABLE t_emc_tipo_telf_func CASCADE CONSTRAINTS;

DROP TABLE t_emc_tpo_telf_cli CASCADE CONSTRAINTS;

DROP TABLE t_emc_video CASCADE CONSTRAINTS;

DROP TABLE t_emc_visualizacao CASCADE CONSTRAINTS;