-- SGBD ORACLE 11 G

DROP SEQUENCE SQ_T_EMC_CATEG_VIDEO;
DROP SEQUENCE SQ_T_EMC_CLI;
DROP SEQUENCE SQ_T_EMC_CLI_EMAIL;
DROP SEQUENCE SQ_T_EMC_DEPARTAMENTO;
DROP SEQUENCE SQ_T_EMC_EMAILV1;
DROP SEQUENCE SQ_T_EMC_EMAILV2;
DROP SEQUENCE SQ_T_EMC_FORNECEDOR;
DROP SEQUENCE SQ_T_EMC_FUNC;
DROP SEQUENCE SQ_T_EMC_FUNC_EMAIL;
DROP SEQUENCE SQ_T_EMC_FUNC_TELF;
DROP SEQUENCE SQ_T_EMC_PROD_CATEGORIA;
DROP SEQUENCE SQ_T_EMC_PROD_FORNECEDOR;
DROP SEQUENCE SQ_T_EMC_PRODUTO;
DROP SEQUENCE SQ_T_EMC_SAC;
DROP SEQUENCE SQ_T_EMC_TELF_CLI;
DROP SEQUENCE SQ_T_EMC_TELF_FUNC;
DROP SEQUENCE SQ_T_EMC_TPO_TELF_CLI;
DROP SEQUENCE SQ_T_EMC_VIDEO;
DROP SEQUENCE SQ_T_EMC_VISUALIZACAO;